/**
 * Integrations Microservice
 * 
 * Handles all external integrations:
 * - Calendar: Google Calendar, Microsoft Calendar, iCloud
 * - Task Management: Jira, Microsoft Planner, Trello, Monday.com
 * 
 * This microservice lightens the main backend by handling all external API communications.
 */

const express = require('express');
const cors = require('cors');
const https = require('https');
const fs = require('fs');
const path = require('path');
const { initializeDatabase } = require('./utils/db-helper');

const logger = {
  info: (msg, ...args) => console.log(`[Integrations] ${msg}`, ...args.map(a => typeof a === 'object' ? JSON.stringify(a) : a)),
  error: (msg, ...args) => console.error(`[Integrations ERROR] ${msg}`, ...args.map(a => typeof a === 'object' ? JSON.stringify(a) : a)),
  warn: (msg, ...args) => console.warn(`[Integrations WARNING] ${msg}`, ...args.map(a => typeof a === 'object' ? JSON.stringify(a) : a))
};

const app = express();
const PORT = process.env.PORT || 8006;

// Middleware - restrict CORS to backend service only
const corsOptions = {
  origin: [
    'http://aicos-backend:3001',
    'https://aicos-backend:3001',
    'http://localhost:3001',  // For development
    'https://localhost:3001'
  ],
  credentials: true,
  methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'],
  allowedHeaders: ['Content-Type', 'Authorization']
};
app.use(cors(corsOptions));
app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ extended: true, limit: '10mb' }));

// Request logging middleware
app.use((req, res, next) => {
  const start = Date.now();
  res.on('finish', () => {
    const duration = Date.now() - start;
    logger.info(`HTTP Request`, {
      method: req.method,
      url: req.url,
      status: res.statusCode,
      duration: `${duration}ms`,
      ip: req.ip,
      userAgent: req.get('user-agent')
    });
  });
  next();
});

// Health check
app.get('/health', (req, res) => {
  res.json({
    status: 'healthy',
    service: 'integrations',
    version: '1.0.0',
    timestamp: new Date().toISOString()
  });
});

// Root endpoint
app.get('/', (req, res) => {
  res.json({
    service: 'AI Chief of Staff - Integrations Service',
    version: '1.0.0',
    endpoints: {
      health: '/health',
      calendar: {
        google: '/calendar/google/*',
        microsoft: '/calendar/microsoft/*',
        icloud: '/calendar/icloud/*'
      },
      tasks: {
        jira: '/tasks/jira/*',
        planner: '/tasks/planner/*',
        trello: '/tasks/trello/*',
        monday: '/tasks/monday/*'
      }
    }
  });
});

// Initialize database and load routes
(async () => {
  try {
    // Initialize database connection
    await initializeDatabase();
    logger.info('Database initialized successfully');
    
    // Import route modules
    const googleCalendarRoutes = require('./routes/google-calendar');
    const microsoftCalendarRoutes = require('./routes/microsoft-calendar');
    const jiraRoutes = require('./routes/jira');
    const plannerRoutes = require('./routes/planner');
    const trelloRoutes = require('./routes/trello');
    const mondayRoutes = require('./routes/monday');
    
    // Register routes
    app.use('/calendar/google', googleCalendarRoutes);
    app.use('/calendar/microsoft', microsoftCalendarRoutes);
    app.use('/tasks/jira', jiraRoutes);
    app.use('/tasks/planner', plannerRoutes);
    app.use('/tasks/trello', trelloRoutes);
    app.use('/tasks/monday', mondayRoutes);
    
    logger.info('All integration routes loaded successfully');
    
    // Error handling middleware (must be after routes)
    app.use((err, req, res, next) => {
      logger.error('Unhandled error:', err);
      res.status(500).json({
        error: 'Internal server error',
        message: err.message
      });
    });

    // 404 handler (must be last)
    app.use((req, res) => {
      res.status(404).json({
        error: 'Not found',
        path: req.path
      });
    });

    // Start server with HTTPS after routes are loaded
    // Certs are generated by generate-service-cert.sh at /app/certs
    const CERT_DIR = '/app/certs';
    const CERT_PATH = path.join(CERT_DIR, 'aicos-integrations.crt');
    const KEY_PATH = path.join(CERT_DIR, 'aicos-integrations.key');

    // Check if certificates exist
    if (fs.existsSync(CERT_PATH) && fs.existsSync(KEY_PATH)) {
      // Start HTTPS server
      const httpsOptions = {
        cert: fs.readFileSync(CERT_PATH),
        key: fs.readFileSync(KEY_PATH)
      };
      
      https.createServer(httpsOptions, app).listen(PORT, '0.0.0.0', () => {
        logger.info(`=== Integrations Service Starting ===`);
        logger.info(`→ Protocol: HTTPS (TLS enabled)`);
        logger.info(`→ Environment: ${process.env.NODE_ENV || 'development'}`);
        logger.info(`→ Port: ${PORT}`);
        logger.info(`→ Database: ${process.env.DATABASE_URL ? 'PostgreSQL' : 'SQLite'}`);
        logger.info(`→ Certificate: ${CERT_PATH}`);
        logger.info(`✓ Server ready and listening`);
        logger.info(`=====================================`);
      });
    } else {
      // Fallback to HTTP if certificates don't exist (shouldn't happen with auto-generation)
      logger.warn('TLS certificates not found, falling back to HTTP');
      logger.warn(`Expected cert at: ${CERT_PATH}`);
      logger.warn(`Expected key at: ${KEY_PATH}`);
      
      app.listen(PORT, '0.0.0.0', () => {
        logger.info(`=== Integrations Service Starting ===`);
        logger.info(`→ Protocol: HTTP (INSECURE)`);
        logger.info(`→ Environment: ${process.env.NODE_ENV || 'development'}`);
        logger.info(`→ Port: ${PORT}`);
        logger.info(`→ Database: ${process.env.DATABASE_URL ? 'PostgreSQL' : 'SQLite'}`);
        logger.info(`✓ Server ready and listening`);
        logger.info(`=====================================`);
      });
    }
  } catch (err) {
    logger.error('Failed to initialize service:', err.message);
    process.exit(1);
  }
})();

module.exports = app;
